services:
  - type: web
    name: lightning-goat-api
    runtime: python
    buildCommand: ./render-build.sh
    startCommand: python -m src.main --host 0.0.0.0 --port 10000
    envVars:
      - key: ENV
        value: production
