services:
  - type: web
    name: quart-api
    env: python
    buildCommand: ./render-build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ENV
        value: production
